# Generated by Django 6.0.6 on 2026-07-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_accounts', '0002_alter_customuser_eta_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='eta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Età'),
        ),
    ]
