# Generated by Django 6.0.6 on 2026-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_accounts', '0003_alter_customuser_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
