# Generated by Django 6.0.6 on 2026-06-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('descrizione_evento', models.TextField()),
                ('luogo_evento', models.CharField(max_length=100)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventi_gestione.tipologia')),
            ],
        ),
    ]
