# Generated by Django 6.0.6 on 2026-06-08 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0002_eventi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='data_ora_evento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
