# Generated by Django 6.0.6 on 2026-06-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0003_eventi_data_ora_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='immagine_evento',
            field=models.ImageField(blank=True, null=True, upload_to='eventi/'),
        ),
        migrations.AlterField(
            model_name='eventi',
            name='data_ora_evento',
            field=models.DateTimeField(),
        ),
    ]
