# Generated by Django 6.0.6 on 2026-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0004_eventi_immagine_evento_alter_eventi_data_ora_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='posti_prenotabili',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
