# Generated by Django 6.0.6 on 2026-06-29 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0006_eventi_creatore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='creatore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tipologie_create', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
