# Generated by Django 6.0.6 on 2026-07-01 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0007_tipologia_creatore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='annullato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventi',
            name='creatore',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'redattori'}, on_delete=django.db.models.deletion.CASCADE, related_name='eventi_creati', to=settings.AUTH_USER_MODEL),
        ),
    ]
