# Generated by Django 6.0.6 on 2026-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0008_eventi_annullato_alter_eventi_creatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='pubblicato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
