# Generated by Django 6.0.6 on 2026-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0009_eventi_pubblicato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventi',
            name='annullato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventi',
            name='pubblicato',
            field=models.BooleanField(default=False),
        ),
    ]
