# Generated by Django 6.0.6 on 2026-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0010_alter_eventi_annullato_alter_eventi_pubblicato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventi',
            name='immagine_evento',
            field=models.ImageField(blank=True, upload_to='eventi/'),
        ),
    ]
