# Generated by Django 6.0.6 on 2026-07-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0011_alter_eventi_immagine_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipologia',
            options={'ordering': ['nome_tipo']},
        ),
    ]
