# Generated by Django 6.0.6 on 2026-07-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0012_alter_tipologia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventi',
            name='prezzo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
