# Generated by Django 6.0.6 on 2026-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_gestione', '0013_eventi_prezzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventi',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='eventi',
            name='tipo_evento',
            field=models.ManyToManyField(related_name='eventi', to='eventi_gestione.tipologia'),
        ),
    ]
